### ISSUE TITLE
Uploading ODM files directly to FHIR server fails

### ISSUE THREAD

**Issue by taneroksuz** [num-codex/odm2fhir#19]
Although the server address **http://localhost:8090/fhir/metadata** can be reached locally, I get following errors when I run the Docker image with the option **--fhir.server.url=http://localhost:8090/fhir**:

```console
2021-02-19 10:20:42.417  WARN 1 --- [           main] d.d.u.o.f.writer.FHIRBundleServerWriter  : Attempt 1 to send bundle failed with error

ca.uhn.fhir.rest.client.exceptions.FhirClientConnectionException: Failed to retrieve the server metadata statement during client initialization. URL used was http://localhost:8090/fhir/metadata
```

**Comment by holger-stenzhorn** [comment]
By default, Docker uses a bridge network for containers and because of that `localhost` refers basically to the container itself and not to the (Docker) host. To solve your issue you can either specify the IP address instead of `localhost` or you can make Docker use the host network by adding `--network=host` as parameter to the `run` command.
